version: '3'

services:

  gptbot:
    container_name: "gptbot-node"
    build: .
    restart: always
    ports:
      - "5001:5001"
    external_links:
      - mongo
    
  mongo:
    container_name: "gptbot-mongo"
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: gptdb
    volumes:
      - ./data:/data/db
    ports:
      - "27012:27017"

  mongo-express:
    container_name: "gptbot-mongo-express"
    image: mongo-express
    ports:
      - "8084:8084"
